version: '2'

services:
  server:
    container_name: server
    build:
      context: ${SERVER_TWO_SRC}
      dockerfile: .docker/local.dockerfile
    ports: 
      - 8080:5000
    volumes:
      - ${SERVER_TWO_SRC}:/app
    networks:
      - test-network

networks:
  test-network:
    driver: bridge